version: "3.9"
services:
  front:
    image: sermalenk/skypro-front:base
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    image: verevkinaee/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_USER: $${USER}
      DB_NAME: $${NAME}
      DB_HOST: $${HOST}
      DB_PASSWORD: $${PASSWORD}
      DEBUG: $${DEBUG}
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  postgres:
        image: postgres
        environment:
          POSTGRES_PASSWORD: ${PASSWORD}
          POSTGRES_USER: ${USER}
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres" ]
          interval: 5s
          timeout: 5s
          retries: 5
        volumes:
                - ./db/:/var/lib/postgresql/data
