version: "3.9"
services:
  front:
    image: sermalenk/skypro-front:base
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    image: verevkinaee/todolist:base
    ports:
      - "8000:8000"
    env_file:
      - ./todolist/.env
    command: >
      sh -c "python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
        image: postgres
        env_file:
          - ./todolist/.env
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres" ]
          interval: 5s
          timeout: 5s
          retries: 5
        volumes:
                - ./db/:/var/lib/postgresql/data
